"""enum.py"""

# pylint: disable=invalid-name

from enum import Enum

import robotis_gz_sim.dsrpy.dsrbind as _dsrb

__all__ = [
    "RobotState",
    "RobotControl",
    "SpeedMode",
    "RobotSystem",
    "UpdateTarget",
    "EncoderPolarity",
    "RobotMode",
    "RobotSpace",
    "JogAxis",
    "JointAxis",
    "TaskAxis",
    "CoordinateSystem",
    "MoveReference",
    "MoveMode",
    "MoveOrientation",
    "SpiralDir",
    "RotDir",
    "PathMode",
    "MoveHome",
    "ControlMode",
    "SingularityAvoidance",
    "BlendingSpeedType",
    "DrServoJType",
    "SafeStopResetType",
    "ManageAccessControl",
    "MonitoringAccessControl",
    "StopType",
    "SplineVelocityOption",
    "DataType",
    "VariableType",
    "SubProgram",
    "GpioCtrlboxDigitalIndex",
    "GpioCtrlboxAnalogIndex",
    "GpioToolAnalogIndex",
    "GpioToolDigitalIndex",
    "DrlProgramState",
    "GpioAnalogType",
    "ModbusRegisterType",
    "ProgramStopCause",
    "MovebBlendingType",
    "ForceAxis",
    "ForceMode",
    "LogLevel",
    "LogGroup",
    "MessageLevel",
    "PopupResponse",
    "RobotAxis",
    "ByteSize",
    "StopBits",
    "ParityCheck",
    "ReleaseMode",
    "CogReference",
    "AddUp",
    "OutputType",
    "SafetyMode",
    "SafetyState",
    "SafetyFunc",
    "SafetyModeEvent",
    "LogGroupSystemFMK",
    "LogGroupMotionLib",
    "LogGroupSafetyController",
    "OpenConnError",
    "ServoOnError",
    "ServoOffError",
    "CloseConnError",
    "ActiveMotion",
    "TrajState",
]


class RobotState(Enum):
    """RobotState"""

    STATE_INITIALIZING = _dsrb.ROBOT_STATE.STATE_INITIALIZING
    STATE_STANDBY = _dsrb.ROBOT_STATE.STATE_STANDBY
    STATE_MOVING = _dsrb.ROBOT_STATE.STATE_MOVING
    STATE_SAFE_OFF = _dsrb.ROBOT_STATE.STATE_SAFE_OFF
    STATE_TEACHING = _dsrb.ROBOT_STATE.STATE_TEACHING
    STATE_SAFE_STOP = _dsrb.ROBOT_STATE.STATE_SAFE_STOP
    STATE_EMERGENCY_STOP = _dsrb.ROBOT_STATE.STATE_EMERGENCY_STOP
    STATE_HOMMING = _dsrb.ROBOT_STATE.STATE_HOMMING
    STATE_RECOVERY = _dsrb.ROBOT_STATE.STATE_RECOVERY
    STATE_SAFE_STOP2 = _dsrb.ROBOT_STATE.STATE_SAFE_STOP2
    STATE_SAFE_OFF2 = _dsrb.ROBOT_STATE.STATE_SAFE_OFF2
    STATE_RESERVED1 = _dsrb.ROBOT_STATE.STATE_RESERVED1
    STATE_RESERVED2 = _dsrb.ROBOT_STATE.STATE_RESERVED2
    STATE_RESERVED3 = _dsrb.ROBOT_STATE.STATE_RESERVED3
    STATE_RESERVED4 = _dsrb.ROBOT_STATE.STATE_RESERVED4
    STATE_NOT_READY = _dsrb.ROBOT_STATE.STATE_NOT_READY
    STATE_LAST = _dsrb.ROBOT_STATE.STATE_LAST


class RobotControl(Enum):
    """RobotControl"""

    CONTROL_INIT_CONFIG = _dsrb.ROBOT_CONTROL.CONTROL_INIT_CONFIG
    CONTROL_ENABLE_OPERATION = _dsrb.ROBOT_CONTROL.CONTROL_ENABLE_OPERATION
    CONTROL_RESET_SAFET_STOP = _dsrb.ROBOT_CONTROL.CONTROL_RESET_SAFET_STOP
    CONTROL_RESET_SAFE_STOP = _dsrb.ROBOT_CONTROL.CONTROL_RESET_SAFE_STOP
    CONTROL_RESET_SAFET_OFF = _dsrb.ROBOT_CONTROL.CONTROL_RESET_SAFET_OFF
    CONTROL_RESET_SAFE_OFF = _dsrb.ROBOT_CONTROL.CONTROL_RESET_SAFE_OFF
    CONTROL_SERVO_ON = _dsrb.ROBOT_CONTROL.CONTROL_SERVO_ON
    CONTROL_RECOVERY_SAFE_STOP = _dsrb.ROBOT_CONTROL.CONTROL_RECOVERY_SAFE_STOP
    CONTROL_RECOVERY_SAFE_OFF = _dsrb.ROBOT_CONTROL.CONTROL_RECOVERY_SAFE_OFF
    CONTROL_RECOVERY_BACKDRIVE = _dsrb.ROBOT_CONTROL.CONTROL_RECOVERY_BACKDRIVE
    CONTROL_RESET_RECOVERY = _dsrb.ROBOT_CONTROL.CONTROL_RESET_RECOVERY
    CONTROL_LAST = _dsrb.ROBOT_CONTROL.CONTROL_LAST


class SpeedMode(Enum):
    """SpeedMode"""

    SPEED_NORMAL_MODE = _dsrb.SPEED_MODE.SPEED_NORMAL_MODE
    SPEED_REDUCED_MODE = _dsrb.SPEED_MODE.SPEED_REDUCED_MODE


class RobotSystem(Enum):
    """RobotSystem"""

    ROBOT_SYSTEM_REAL = _dsrb.ROBOT_SYSTEM.ROBOT_SYSTEM_REAL
    ROBOT_SYSTEM_VIRTUAL = _dsrb.ROBOT_SYSTEM.ROBOT_SYSTEM_VIRTUAL
    ROBOT_SYSTEM_LAST = _dsrb.ROBOT_SYSTEM.ROBOT_SYSTEM_LAST


class UpdateTarget(Enum):
    """UpdateTarget"""

    UPDATE_TARGET_FIRST = _dsrb.UPDATE_TARGET.UPDATE_TARGET_FIRST
    UPDATE_TARGET_INVETER_1 = _dsrb.UPDATE_TARGET.UPDATE_TARGET_INVETER_1
    UPDATE_TARGET_INVETER_2 = _dsrb.UPDATE_TARGET.UPDATE_TARGET_INVETER_2
    UPDATE_TARGET_INVETER_3 = _dsrb.UPDATE_TARGET.UPDATE_TARGET_INVETER_3
    UPDATE_TARGET_INVETER_4 = _dsrb.UPDATE_TARGET.UPDATE_TARGET_INVETER_4
    UPDATE_TARGET_INVETER_5 = _dsrb.UPDATE_TARGET.UPDATE_TARGET_INVETER_5
    UPDATE_TARGET_INVETER_6 = _dsrb.UPDATE_TARGET.UPDATE_TARGET_INVETER_6
    UPDATE_TARGET_INVETER_LAST = _dsrb.UPDATE_TARGET.UPDATE_TARGET_INVETER_LAST
    UPDATE_TARGET_SAFETYBD = _dsrb.UPDATE_TARGET.UPDATE_TARGET_SAFETYBD
    UPDATE_TARGET_CONTROLLER = _dsrb.UPDATE_TARGET.UPDATE_TARGET_CONTROLLER
    UPDATE_TARGET_SVM = _dsrb.UPDATE_TARGET.UPDATE_TARGET_SVM
    UPDATE_TARGET_LAST = _dsrb.UPDATE_TARGET.UPDATE_TARGET_LAST


class EncoderPolarity(Enum):
    """EncoderPolarity"""

    ENCORDER_POLARITY_A = _dsrb.ENCORDER_POLARITY.ENCORDER_POLARITY_A
    ENCORDER_POLARITY_B = _dsrb.ENCORDER_POLARITY.ENCORDER_POLARITY_B
    ENCORDER_POLARITY_Z = _dsrb.ENCORDER_POLARITY.ENCORDER_POLARITY_Z
    ENCORDER_POLARITY_S = _dsrb.ENCORDER_POLARITY.ENCORDER_POLARITY_S
    ENCORDER_POLARITY_LAST = _dsrb.ENCORDER_POLARITY.ENCORDER_POLARITY_LAST


class RobotMode(Enum):
    """RobotMode"""

    ROBOT_MODE_MANUAL = _dsrb.ROBOT_MODE.ROBOT_MODE_MANUAL
    ROBOT_MODE_AUTONOMOUS = _dsrb.ROBOT_MODE.ROBOT_MODE_AUTONOMOUS
    ROBOT_MODE_RECOVERY = _dsrb.ROBOT_MODE.ROBOT_MODE_RECOVERY
    ROBOT_MODE_BACKDRIVE = _dsrb.ROBOT_MODE.ROBOT_MODE_BACKDRIVE
    ROBOT_MODE_MEASURE = _dsrb.ROBOT_MODE.ROBOT_MODE_MEASURE
    ROBOT_MODE_INITIALIZE = _dsrb.ROBOT_MODE.ROBOT_MODE_INITIALIZE
    ROBOT_MODE_LAST = _dsrb.ROBOT_MODE.ROBOT_MODE_LAST


class RobotSpace(Enum):
    """RobotSpace"""

    ROBOT_SPACE_JOINT = _dsrb.ROBOT_SPACE.ROBOT_SPACE_JOINT
    ROBOT_SPACE_TASK = _dsrb.ROBOT_SPACE.ROBOT_SPACE_TASK


class JogAxis(Enum):
    """JogAxis"""

    JOG_AXIS_JOINT_1 = _dsrb.JOG_AXIS.JOG_AXIS_JOINT_1
    JOG_AXIS_JOINT_2 = _dsrb.JOG_AXIS.JOG_AXIS_JOINT_2
    JOG_AXIS_JOINT_3 = _dsrb.JOG_AXIS.JOG_AXIS_JOINT_3
    JOG_AXIS_JOINT_4 = _dsrb.JOG_AXIS.JOG_AXIS_JOINT_4
    JOG_AXIS_JOINT_5 = _dsrb.JOG_AXIS.JOG_AXIS_JOINT_5
    JOG_AXIS_JOINT_6 = _dsrb.JOG_AXIS.JOG_AXIS_JOINT_6
    JOG_AXIS_TASK_X = _dsrb.JOG_AXIS.JOG_AXIS_TASK_X
    JOG_AXIS_TASK_Y = _dsrb.JOG_AXIS.JOG_AXIS_TASK_Y
    JOG_AXIS_TASK_Z = _dsrb.JOG_AXIS.JOG_AXIS_TASK_Z
    JOG_AXIS_TASK_RX = _dsrb.JOG_AXIS.JOG_AXIS_TASK_RX
    JOG_AXIS_TASK_RY = _dsrb.JOG_AXIS.JOG_AXIS_TASK_RY
    JOG_AXIS_TASK_RZ = _dsrb.JOG_AXIS.JOG_AXIS_TASK_RZ


class JointAxis(Enum):
    """JointAxis"""

    JOINT_AXIS_1 = _dsrb.JOINT_AXIS.JOINT_AXIS_1
    JOINT_AXIS_2 = _dsrb.JOINT_AXIS.JOINT_AXIS_2
    JOINT_AXIS_3 = _dsrb.JOINT_AXIS.JOINT_AXIS_3
    JOINT_AXIS_4 = _dsrb.JOINT_AXIS.JOINT_AXIS_4
    JOINT_AXIS_5 = _dsrb.JOINT_AXIS.JOINT_AXIS_5
    JOINT_AXIS_6 = _dsrb.JOINT_AXIS.JOINT_AXIS_6


class TaskAxis(Enum):
    """TaskAxis"""

    TASK_AXIS_X = _dsrb.TASK_AXIS.TASK_AXIS_X
    TASK_AXIS_Y = _dsrb.TASK_AXIS.TASK_AXIS_Y
    TASK_AXIS_Z = _dsrb.TASK_AXIS.TASK_AXIS_Z


class CoordinateSystem(Enum):
    """CoordinateSystem"""

    COORDINATE_SYSTEM_BASE = _dsrb.COORDINATE_SYSTEM.COORDINATE_SYSTEM_BASE
    COORDINATE_SYSTEM_TOOL = _dsrb.COORDINATE_SYSTEM.COORDINATE_SYSTEM_TOOL
    COORDINATE_SYSTEM_WORLD = _dsrb.COORDINATE_SYSTEM.COORDINATE_SYSTEM_WORLD
    COORDINATE_SYSTEM_USER_MIN = (
        _dsrb.COORDINATE_SYSTEM.COORDINATE_SYSTEM_USER_MIN
    )
    COORDINATE_SYSTEM_USER_MAX = (
        _dsrb.COORDINATE_SYSTEM.COORDINATE_SYSTEM_USER_MAX
    )


class MoveReference(Enum):
    """MoveReference"""

    MOVE_REFERENCE_BASE = _dsrb.MOVE_REFERENCE.MOVE_REFERENCE_BASE
    MOVE_REFERENCE_TOOL = _dsrb.MOVE_REFERENCE.MOVE_REFERENCE_TOOL
    MOVE_REFERENCE_WORLD = _dsrb.MOVE_REFERENCE.MOVE_REFERENCE_WORLD
    MOVE_REFERENCE_USER_MIN = _dsrb.MOVE_REFERENCE.MOVE_REFERENCE_USER_MIN
    MOVE_REFERENCE_USER_MAX = _dsrb.MOVE_REFERENCE.MOVE_REFERENCE_USER_MAX


class MoveMode(Enum):
    """MoveMode"""

    MOVE_MODE_ABSOLUTE = _dsrb.MOVE_MODE.MOVE_MODE_ABSOLUTE
    MOVE_MODE_RELATIVE = _dsrb.MOVE_MODE.MOVE_MODE_RELATIVE


class MoveOrientation(Enum):
    """MoveOrientation"""

    DR_MV_ORI_TEACH = _dsrb.MOVE_ORIENTATION.DR_MV_ORI_TEACH
    DR_MV_ORI_FIXED = _dsrb.MOVE_ORIENTATION.DR_MV_ORI_FIXED
    DR_MV_ORI_RADIAL = _dsrb.MOVE_ORIENTATION.DR_MV_ORI_RADIAL
    DR_MV_ORI_INTENT = _dsrb.MOVE_ORIENTATION.DR_MV_ORI_INTENT


class SpiralDir(Enum):
    """SpiralDir"""

    DR_SPIRAL_OUTWARD = _dsrb.SPIRAL_DIR.DR_SPIRAL_OUTWARD
    DR_SPIRAL_INWARD = _dsrb.SPIRAL_DIR.DR_SPIRAL_INWARD


class RotDir(Enum):
    """RotDir"""

    DR_ROT_FORWARD = _dsrb.ROT_DIR.DR_ROT_FORWARD
    DR_ROT_REVERSE = _dsrb.ROT_DIR.DR_ROT_REVERSE


class PathMode(Enum):
    """PathMode"""

    PATH_MODE_DPOS = _dsrb.PATH_MODE.PATH_MODE_DPOS
    PATH_MODE_DVEL = _dsrb.PATH_MODE.PATH_MODE_DVEL


class MoveHome(Enum):
    """MoveHome"""

    MOVE_HOME_MECHANIC = _dsrb.MOVE_HOME.MOVE_HOME_MECHANIC
    MOVE_HOME_USER = _dsrb.MOVE_HOME.MOVE_HOME_USER


class ControlMode(Enum):
    """ControlMode"""

    CONTROL_MODE_POSITION = _dsrb.CONTROL_MODE.CONTROL_MODE_POSITION
    CONTROL_MODE_TORQUE = _dsrb.CONTROL_MODE.CONTROL_MODE_TORQUE


class SingularityAvoidance(Enum):
    """SingularityAvoidance"""

    SINGULARITY_AVOIDANCE_AVOID = (
        _dsrb.SINGULARITY_AVOIDANCE.SINGULARITY_AVOIDANCE_AVOID
    )
    SINGULARITY_AVOIDANCE_STOP = (
        _dsrb.SINGULARITY_AVOIDANCE.SINGULARITY_AVOIDANCE_STOP
    )
    SINGULARITY_AVOIDANCE_VEL = (
        _dsrb.SINGULARITY_AVOIDANCE.SINGULARITY_AVOIDANCE_VEL
    )


class BlendingSpeedType(Enum):
    """BlendingSpeedType"""

    BLENDING_SPEED_TYPE_DUPLICATE = (
        _dsrb.BLENDING_SPEED_TYPE.BLENDING_SPEED_TYPE_DUPLICATE
    )
    BLENDING_SPEED_TYPE_OVERRIDE = (
        _dsrb.BLENDING_SPEED_TYPE.BLENDING_SPEED_TYPE_OVERRIDE
    )


class DrServoJType(Enum):
    """DrServoJType"""

    DR_SERVO_OVERRIDE = _dsrb.DR_SERVOJ_TYPE.DR_SERVO_OVERRIDE
    DR_SERVO_QUEUE = _dsrb.DR_SERVOJ_TYPE.DR_SERVO_QUEUE


class SafeStopResetType(Enum):
    """SafeStopResetType"""

    SAFE_STOP_RESET_TYPE_DEFAULT = (
        _dsrb.SAFE_STOP_RESET_TYPE.SAFE_STOP_RESET_TYPE_DEFAULT
    )
    SAFE_STOP_RESET_TYPE_PROGRAM_STOP = (
        _dsrb.SAFE_STOP_RESET_TYPE.SAFE_STOP_RESET_TYPE_PROGRAM_STOP
    )
    SAFE_STOP_RESET_TYPE_PROGRAM_RESUME = (
        _dsrb.SAFE_STOP_RESET_TYPE.SAFE_STOP_RESET_TYPE_PROGRAM_RESUME
    )


class ManageAccessControl(Enum):
    """ManageAccessControl"""

    MANAGE_ACCESS_CONTROL_FORCE_REQUEST = (
        _dsrb.MANAGE_ACCESS_CONTROL.MANAGE_ACCESS_CONTROL_FORCE_REQUEST
    )
    MANAGE_ACCESS_CONTROL_REQUEST = (
        _dsrb.MANAGE_ACCESS_CONTROL.MANAGE_ACCESS_CONTROL_REQUEST
    )
    MANAGE_ACCESS_CONTROL_RESPONSE_YES = (
        _dsrb.MANAGE_ACCESS_CONTROL.MANAGE_ACCESS_CONTROL_RESPONSE_YES
    )
    MANAGE_ACCESS_CONTROL_RESPONSE_NO = (
        _dsrb.MANAGE_ACCESS_CONTROL.MANAGE_ACCESS_CONTROL_RESPONSE_NO
    )


class MonitoringAccessControl(Enum):
    """MonitoringAccessControl"""

    MONITORING_ACCESS_CONTROL_REQUEST = (
        _dsrb.MONITORING_ACCESS_CONTROL.MONITORING_ACCESS_CONTROL_REQUEST
    )
    MONITORING_ACCESS_CONTROL_DENY = (
        _dsrb.MONITORING_ACCESS_CONTROL.MONITORING_ACCESS_CONTROL_DENY
    )
    MONITORING_ACCESS_CONTROL_GRANT = (
        _dsrb.MONITORING_ACCESS_CONTROL.MONITORING_ACCESS_CONTROL_GRANT
    )
    MONITORING_ACCESS_CONTROL_LOSS = (
        _dsrb.MONITORING_ACCESS_CONTROL.MONITORING_ACCESS_CONTROL_LOSS
    )
    MONITORING_ACCESS_CONTROL_LAST = (
        _dsrb.MONITORING_ACCESS_CONTROL.MONITORING_ACCESS_CONTROL_LAST
    )


class StopType(Enum):
    """StopType"""

    STOP_TYPE_QUICK_STO = _dsrb.STOP_TYPE.STOP_TYPE_QUICK_STO
    STOP_TYPE_QUICK = _dsrb.STOP_TYPE.STOP_TYPE_QUICK
    STOP_TYPE_SLOW = _dsrb.STOP_TYPE.STOP_TYPE_SLOW
    STOP_TYPE_HOLD = _dsrb.STOP_TYPE.STOP_TYPE_HOLD
    STOP_TYPE_EMERGENCY = _dsrb.STOP_TYPE.STOP_TYPE_EMERGENCY


class SplineVelocityOption(Enum):
    """SplineVelocityOption"""

    SPLINE_VELOCITY_OPTION_DEFAULT = (
        _dsrb.SPLINE_VELOCITY_OPTION.SPLINE_VELOCITY_OPTION_DEFAULT
    )
    SPLINE_VELOCITY_OPTION_CONST = (
        _dsrb.SPLINE_VELOCITY_OPTION.SPLINE_VELOCITY_OPTION_CONST
    )


class DataType(Enum):
    """DataType"""

    DATA_TYPE_BOOL = _dsrb.DATA_TYPE.DATA_TYPE_BOOL
    DATA_TYPE_INT = _dsrb.DATA_TYPE.DATA_TYPE_INT
    DATA_TYPE_FLOAT = _dsrb.DATA_TYPE.DATA_TYPE_FLOAT
    DATA_TYPE_STRING = _dsrb.DATA_TYPE.DATA_TYPE_STRING
    DATA_TYPE_POSJ = _dsrb.DATA_TYPE.DATA_TYPE_POSJ
    DATA_TYPE_POSX = _dsrb.DATA_TYPE.DATA_TYPE_POSX
    DATA_TYPE_UNKNOWN = _dsrb.DATA_TYPE.DATA_TYPE_UNKNOWN


class VariableType(Enum):
    """VariableType"""

    VARIABLE_TYPE_INSTALL = _dsrb.VARIABLE_TYPE.VARIABLE_TYPE_INSTALL
    VARIABLE_TYPE_GLOBAL = _dsrb.VARIABLE_TYPE.VARIABLE_TYPE_GLOBAL


class SubProgram(Enum):
    """SubProgram"""

    SUB_PROGRAM_DELETE = _dsrb.SUB_PROGRAM.SUB_PROGRAM_DELETE
    SUB_PROGRAM_SAVE = _dsrb.SUB_PROGRAM.SUB_PROGRAM_SAVE


class GpioCtrlboxDigitalIndex(Enum):
    """GpioCtrlboxDigitalIndex"""

    GPIO_CTRLBOX_DIGITAL_INDEX_1 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_1
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_2 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_2
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_3 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_3
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_4 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_4
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_5 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_5
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_6 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_6
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_7 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_7
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_8 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_8
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_9 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_9
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_10 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_10
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_11 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_11
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_12 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_12
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_13 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_13
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_14 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_14
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_15 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_15
    )
    GPIO_CTRLBOX_DIGITAL_INDEX_16 = (
        _dsrb.GPIO_CTRLBOX_DIGITAL_INDEX.GPIO_CTRLBOX_DIGITAL_INDEX_16
    )


class GpioCtrlboxAnalogIndex(Enum):
    """GpioCtrlboxAnalogIndex"""

    GPIO_CTRLBOX_ANALOG_INDEX_1 = (
        _dsrb.GPIO_CTRLBOX_ANALOG_INDEX.GPIO_CTRLBOX_ANALOG_INDEX_1
    )
    GPIO_CTRLBOX_ANALOG_INDEX_2 = (
        _dsrb.GPIO_CTRLBOX_ANALOG_INDEX.GPIO_CTRLBOX_ANALOG_INDEX_2
    )


class GpioToolAnalogIndex(Enum):
    """GpioToolAnalogIndex"""

    GPIO_TOOL_ANALOG_INDEX_1 = (
        _dsrb.GPIO_TOOL_ANALOG_INDEX.GPIO_TOOL_ANALOG_INDEX_1
    )
    GPIO_TOOL_ANALOG_INDEX_2 = (
        _dsrb.GPIO_TOOL_ANALOG_INDEX.GPIO_TOOL_ANALOG_INDEX_2
    )


class GpioToolDigitalIndex(Enum):
    """GpioToolDigitalIndex"""

    GPIO_TOOL_DIGITAL_INDEX_1 = (
        _dsrb.GPIO_TOOL_DIGITAL_INDEX.GPIO_TOOL_DIGITAL_INDEX_1
    )
    GPIO_TOOL_DIGITAL_INDEX_2 = (
        _dsrb.GPIO_TOOL_DIGITAL_INDEX.GPIO_TOOL_DIGITAL_INDEX_2
    )
    GPIO_TOOL_DIGITAL_INDEX_3 = (
        _dsrb.GPIO_TOOL_DIGITAL_INDEX.GPIO_TOOL_DIGITAL_INDEX_3
    )
    GPIO_TOOL_DIGITAL_INDEX_4 = (
        _dsrb.GPIO_TOOL_DIGITAL_INDEX.GPIO_TOOL_DIGITAL_INDEX_4
    )
    GPIO_TOOL_DIGITAL_INDEX_5 = (
        _dsrb.GPIO_TOOL_DIGITAL_INDEX.GPIO_TOOL_DIGITAL_INDEX_5
    )
    GPIO_TOOL_DIGITAL_INDEX_6 = (
        _dsrb.GPIO_TOOL_DIGITAL_INDEX.GPIO_TOOL_DIGITAL_INDEX_6
    )


class DrlProgramState(Enum):
    """DrlProgramState"""

    DRL_PROGRAM_STATE_PLAY = _dsrb.DRL_PROGRAM_STATE.DRL_PROGRAM_STATE_PLAY
    DRL_PROGRAM_STATE_STOP = _dsrb.DRL_PROGRAM_STATE.DRL_PROGRAM_STATE_STOP
    DRL_PROGRAM_STATE_HOLD = _dsrb.DRL_PROGRAM_STATE.DRL_PROGRAM_STATE_HOLD
    DRL_PROGRAM_STATE_LAST = _dsrb.DRL_PROGRAM_STATE.DRL_PROGRAM_STATE_LAST


class GpioAnalogType(Enum):
    """GpioAnalogType"""

    GPIO_ANALOG_TYPE_CURRENT = _dsrb.GPIO_ANALOG_TYPE.GPIO_ANALOG_TYPE_CURRENT
    GPIO_ANALOG_TYPE_VOLTAGE = _dsrb.GPIO_ANALOG_TYPE.GPIO_ANALOG_TYPE_VOLTAGE


class ModbusRegisterType(Enum):
    """Modbus Register Type"""

    MODBUS_REGISTER_TYPE_DISCRETE_INPUTS = (
        _dsrb.MODBUS_REGISTER_TYPE.MODBUS_REGISTER_TYPE_DISCRETE_INPUTS
    )
    MODBUS_REGISTER_TYPE_COILS = (
        _dsrb.MODBUS_REGISTER_TYPE.MODBUS_REGISTER_TYPE_COILS
    )
    MODBUS_REGISTER_TYPE_INPUT_REGISTER = (
        _dsrb.MODBUS_REGISTER_TYPE.MODBUS_REGISTER_TYPE_INPUT_REGISTER
    )
    MODBUS_REGISTER_TYPE_HOLDING_REGISTER = (
        _dsrb.MODBUS_REGISTER_TYPE.MODBUS_REGISTER_TYPE_HOLDING_REGISTER
    )


class ProgramStopCause(Enum):
    """Program Stop Cause"""

    PROGRAM_STOP_CAUSE_NORMAL = (
        _dsrb.PROGRAM_STOP_CAUSE.PROGRAM_STOP_CAUSE_NORMAL
    )
    PROGRAM_STOP_CAUSE_FORCE = _dsrb.PROGRAM_STOP_CAUSE.PROGRAM_STOP_CAUSE_FORCE
    PROGRAM_STOP_CAUSE_ERROR = _dsrb.PROGRAM_STOP_CAUSE.PROGRAM_STOP_CAUSE_ERROR
    PROGRAM_STOP_CAUSE_LAST = _dsrb.PROGRAM_STOP_CAUSE.PROGRAM_STOP_CAUSE_LAST


class MovebBlendingType(Enum):
    """MoveB Blending Type"""

    MOVEB_BLENDING_TYPE_LINE = (
        _dsrb.MOVEB_BLENDING_TYPE.MOVEB_BLENDING_TYPE_LINE
    )
    MOVEB_BLENDING_TYPE_CIRLCE = (
        _dsrb.MOVEB_BLENDING_TYPE.MOVEB_BLENDING_TYPE_CIRLCE
    )


class ForceAxis(Enum):
    """Force Axis"""

    FORCE_AXIS_X = _dsrb.FORCE_AXIS.FORCE_AXIS_X
    FORCE_AXIS_Y = _dsrb.FORCE_AXIS.FORCE_AXIS_Y
    FORCE_AXIS_Z = _dsrb.FORCE_AXIS.FORCE_AXIS_Z
    FORCE_AXIS_A = _dsrb.FORCE_AXIS.FORCE_AXIS_A
    FORCE_AXIS_B = _dsrb.FORCE_AXIS.FORCE_AXIS_B
    FORCE_AXIS_C = _dsrb.FORCE_AXIS.FORCE_AXIS_C


class ForceMode(Enum):
    """Force Mode"""

    FORCE_MODE_ABSOLUTE = _dsrb.FORCE_MODE.FORCE_MODE_ABSOLUTE
    FORCE_MODE_RELATIVE = _dsrb.FORCE_MODE.FORCE_MODE_RELATIVE


class LogLevel(Enum):
    """Log Level"""

    LOG_LEVEL_RESERVED = 0
    LOG_LEVEL_SYSINFO = _dsrb.LOG_LEVEL.LOG_LEVEL_SYSINFO
    LOG_LEVEL_SYSWARN = _dsrb.LOG_LEVEL.LOG_LEVEL_SYSWARN
    LOG_LEVEL_SYSERROR = _dsrb.LOG_LEVEL.LOG_LEVEL_SYSERROR
    LOG_LEVEL_LAST = _dsrb.LOG_LEVEL.LOG_LEVEL_LAST


class LogGroup(Enum):
    """Log Group"""

    LOG_GROUP_RESERVED = 0
    LOG_GROUP_SYSTEMFMK = _dsrb.LOG_GROUP.LOG_GROUP_SYSTEMFMK
    LOG_GROUP_MOTIONLIB = _dsrb.LOG_GROUP.LOG_GROUP_MOTIONLIB
    LOG_GROUP_SMARTTP = _dsrb.LOG_GROUP.LOG_GROUP_SMARTTP
    LOG_GROUP_INVERTER = _dsrb.LOG_GROUP.LOG_GROUP_INVERTER
    LOG_GROUP_SAFETYCONTROLLER = _dsrb.LOG_GROUP.LOG_GROUP_SAFETYCONTROLLER
    LOG_GROUP_LAST = _dsrb.LOG_GROUP.LOG_GROUP_LAST


class MessageLevel(Enum):
    """Message Level"""

    MESSAGE_LEVEL_INFO = _dsrb.MESSAGE_LEVEL.MESSAGE_LEVEL_INFO
    MESSAGE_LEVEL_WARN = _dsrb.MESSAGE_LEVEL.MESSAGE_LEVEL_WARN
    MESSAGE_LEVEL_ALARM = _dsrb.MESSAGE_LEVEL.MESSAGE_LEVEL_ALARM


class PopupResponse(Enum):
    """Popup Response"""

    POPUP_RESPONSE_STOP = _dsrb.POPUP_RESPONSE.POPUP_RESPONSE_STOP
    POPUP_RESPONSE_RESUME = _dsrb.POPUP_RESPONSE.POPUP_RESPONSE_RESUME


class RobotAxis(Enum):
    """Robot Axis"""

    ROBOT_AXIS_1 = _dsrb.ROBOT_AXIS.ROBOT_AXIS_1
    ROBOT_AXIS_2 = _dsrb.ROBOT_AXIS.ROBOT_AXIS_2
    ROBOT_AXIS_3 = _dsrb.ROBOT_AXIS.ROBOT_AXIS_3
    ROBOT_AXIS_4 = _dsrb.ROBOT_AXIS.ROBOT_AXIS_4
    ROBOT_AXIS_5 = _dsrb.ROBOT_AXIS.ROBOT_AXIS_5
    ROBOT_AXIS_6 = _dsrb.ROBOT_AXIS.ROBOT_AXIS_6
    ROBOT_AXIS_ALL = _dsrb.ROBOT_AXIS.ROBOT_AXIS_ALL


class ByteSize(Enum):
    """Byte Size"""

    BYTE_SIZE_FIVEBITES = _dsrb.BYTE_SIZE.BYTE_SIZE_FIVEBITES
    BYTE_SIZE_SIXBITS = _dsrb.BYTE_SIZE.BYTE_SIZE_SIXBITS
    BYTE_SIZE_SEVENBITS = _dsrb.BYTE_SIZE.BYTE_SIZE_SEVENBITS
    BYTE_SIZE_EIGHTBITS = _dsrb.BYTE_SIZE.BYTE_SIZE_EIGHTBITS


class StopBits(Enum):
    """Stop Bits"""

    STOPBITS_ONE = _dsrb.STOP_BITS.STOPBITS_ONE
    STOPBITS_TWO = _dsrb.STOP_BITS.STOPBITS_TWO


class ParityCheck(Enum):
    """Parity Check"""

    PARITY_CHECK_NONE = _dsrb.PARITY_CHECK.PARITY_CHECK_NONE
    PARITY_CHECK_EVEN = _dsrb.PARITY_CHECK.PARITY_CHECK_EVEN
    PARITY_CHECK_ODD = _dsrb.PARITY_CHECK.PARITY_CHECK_ODD


class ReleaseMode(Enum):
    """Release Mode"""

    RELEASE_MODE_STOP = _dsrb.RELEASE_MODE.RELEASE_MODE_STOP
    RELEASE_MODE_RESUME = _dsrb.RELEASE_MODE.RELEASE_MODE_RESUME
    RELEASE_MODE_RELEASE = _dsrb.RELEASE_MODE.RELEASE_MODE_RELEASE
    RELEASE_MODE_RESET = _dsrb.RELEASE_MODE.RELEASE_MODE_RESET


class CogReference(Enum):
    """Cog Reference"""

    COG_REFERENCE_TCP = _dsrb.COG_REFERENCE.COG_REFERENCE_TCP
    COG_REFERENCE_FLANGE = _dsrb.COG_REFERENCE.COG_REFERENCE_FLANGE


class AddUp(Enum):
    """Add Up Modes"""

    ADD_UP_REPLACE = _dsrb.ADD_UP.ADD_UP_REPLACE
    ADD_UP_ADD = _dsrb.ADD_UP.ADD_UP_ADD
    ADD_UP_REMOVE = _dsrb.ADD_UP.ADD_UP_REMOVE


class OutputType(Enum):
    """Output Type"""

    OUTPUT_TYPE_PNP = _dsrb.OUTPUT_TYPE.OUTPUT_TYPE_PNP
    OUTPUT_TYPE_NPN = _dsrb.OUTPUT_TYPE.OUTPUT_TYPE_NPN


class SafetyMode(Enum):
    """Safety Modes"""

    SAFETY_MODE_MANUAL = _dsrb.SAFETY_MODE.SAFETY_MODE_MANUAL
    SAFETY_MODE_AUTONOMOUS = _dsrb.SAFETY_MODE.SAFETY_MODE_AUTONOMOUS
    SAFETY_MODE_RECOVERY = _dsrb.SAFETY_MODE.SAFETY_MODE_RECOVERY
    SAFETY_MODE_BACKDRIVE = _dsrb.SAFETY_MODE.SAFETY_MODE_BACKDRIVE
    SAFETY_MODE_MEASURE = _dsrb.SAFETY_MODE.SAFETY_MODE_MEASURE
    SAFETY_MODE_INITIALIZE = _dsrb.SAFETY_MODE.SAFETY_MODE_INITIALIZE
    SAFETY_MODE_LAST = _dsrb.SAFETY_MODE.SAFETY_MODE_LAST


class SafetyState(Enum):
    """Safety States"""

    SAFETY_STATE_BP_START = _dsrb.SAFETY_STATE.SAFETY_STATE_BP_START
    SAFETY_STATE_BP_INIT = _dsrb.SAFETY_STATE.SAFETY_STATE_BP_INIT
    SAFETY_STATE_VD_STO = _dsrb.SAFETY_STATE.SAFETY_STATE_VD_STO
    SAFETY_STATE_VD_SOS = _dsrb.SAFETY_STATE.SAFETY_STATE_VD_SOS
    SAFETY_STATE_JH_SOS = _dsrb.SAFETY_STATE.SAFETY_STATE_JH_SOS
    SAFETY_STATE_JH_MOVE = _dsrb.SAFETY_STATE.SAFETY_STATE_JH_MOVE
    SAFETY_STATE_HG_MOVE = _dsrb.SAFETY_STATE.SAFETY_STATE_HG_MOVE
    SAFETY_STATE_RV_SOS = _dsrb.SAFETY_STATE.SAFETY_STATE_RV_SOS
    SAFETY_STATE_RV_MOVE = _dsrb.SAFETY_STATE.SAFETY_STATE_RV_MOVE
    SAFETY_STATE_RV_BACK = _dsrb.SAFETY_STATE.SAFETY_STATE_RV_BACK
    SAFETY_STATE_RV_HG_MOVE = _dsrb.SAFETY_STATE.SAFETY_STATE_RV_HG_MOVE
    SAFETY_STATE_SW_SOS = _dsrb.SAFETY_STATE.SAFETY_STATE_SW_SOS
    SAFETY_STATE_SW_RUN = _dsrb.SAFETY_STATE.SAFETY_STATE_SW_RUN
    SAFETY_STATE_CW_SOS = _dsrb.SAFETY_STATE.SAFETY_STATE_CW_SOS
    SAFETY_STATE_CW_RUN = _dsrb.SAFETY_STATE.SAFETY_STATE_CW_RUN
    SAFETY_STATE_CM_RUN = _dsrb.SAFETY_STATE.SAFETY_STATE_CM_RUN
    SAFETY_STATE_AM_RUN = _dsrb.SAFETY_STATE.SAFETY_STATE_AM_RUN
    SAFETY_STATE_DRL_JH_SOS = _dsrb.SAFETY_STATE.SAFETY_STATE_DRL_JH_SOS
    SAFETY_STATE_DRL_HG_MOVE = _dsrb.SAFETY_STATE.SAFETY_STATE_DRL_HG_MOVE
    SAFETY_STATE_LAST = _dsrb.SAFETY_STATE.SAFETY_STATE_LAST


class SafetyFunc(Enum):
    """Safety Functions"""

    SAFETY_FUNC_FIRST = _dsrb.SAFETY_FUNC.SAFETY_FUNC_FIRST
    SAFETY_FUNC_STOP_STO_NOT_USE = (
        _dsrb.SAFETY_FUNC.SAFETY_FUNC_STOP_STO_NOT_USE
    )
    SAFETY_FUNC_STOP_SBC_NOT_USE = (
        _dsrb.SAFETY_FUNC.SAFETY_FUNC_STOP_SBC_NOT_USE
    )
    SAFETY_FUNC_STOP_SS1_NOT_USE = (
        _dsrb.SAFETY_FUNC.SAFETY_FUNC_STOP_SS1_NOT_USE
    )
    SAFETY_FUNC_STOP_SS2_NOT_USE = (
        _dsrb.SAFETY_FUNC.SAFETY_FUNC_STOP_SS2_NOT_USE
    )
    SAFETY_FUNC_SIGNAL_EMG = _dsrb.SAFETY_FUNC.SAFETY_FUNC_SIGNAL_EMG
    SAFETY_FUNC_SIGNAL_PRS = _dsrb.SAFETY_FUNC.SAFETY_FUNC_SIGNAL_PRS
    SAFETY_FUNC_ERROR_SOS = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_SOS
    SAFETY_FUNC_ERROR_JOINT_SLP = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_JOINT_SLP
    SAFETY_FUNC_ERROR_JOINT_SLS = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_JOINT_SLS
    SAFETY_FUNC_ERROR_JOINT_SLT = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_JOINT_SLT
    SAFETY_FUNC_ERROR_COLLISION = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_COLLISION
    SAFETY_FUNC_ERROR_TCP_SLP = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_TCP_SLP
    SAFETY_FUNC_ERROR_TCP_SLO = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_TCP_SLO
    SAFETY_FUNC_ERROR_TCP_SLS = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_TCP_SLS
    SAFETY_FUNC_ERROR_TCP_SLF = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_TCP_SLF
    SAFETY_FUNC_ERROR_MOMENTUM = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_MOMENTUM
    SAFETY_FUNC_ERROR_POWER = _dsrb.SAFETY_FUNC.SAFETY_FUNC_ERROR_POWER
    SAFETY_FUNC_LAST = _dsrb.SAFETY_FUNC.SAFETY_FUNC_LAST
    SAFETY_FUNC_ENABLE_SWITCH_RELEASE = (
        _dsrb.SAFETY_FUNC.SAFETY_FUNC_ENABLE_SWITCH_RELEASE
    )


class SafetyModeEvent(Enum):
    """Safety Mode Events"""

    SAFETY_MODE_EVENT_ENTER = _dsrb.SAFETY_MODE_EVENT.SAFETY_MODE_EVENT_ENTER
    SAFETY_MODE_EVENT_MOVE = _dsrb.SAFETY_MODE_EVENT.SAFETY_MODE_EVENT_MOVE
    SAFETY_MODE_EVENT_STOP = _dsrb.SAFETY_MODE_EVENT.SAFETY_MODE_EVENT_STOP
    SAFETY_MODE_EVENT_LAST = _dsrb.SAFETY_MODE_EVENT.SAFETY_MODE_EVENT_LAST


class LogGroupSystemFMK(Enum):
    """Log Group SystemFMK"""

    OPERATION_FRAMEWORK_START = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_FRAMEWORK_START
    )
    OPERATION_FRAMEWORK_START_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_FRAMEWORK_START_FAILED
    )
    OPERATION_FRAMEWORK_STOP = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_FRAMEWORK_STOP
    )
    COMMAND_SYSTEM_SHUTDOWN = _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_SYSTEM_SHUTDOWN
    COMMAND_SYSTEM_RESTART = _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_SYSTEM_RESTART
    COMMAND_SET_TIME = _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_SET_TIME
    COMMAND_SET_IPADDRESS = _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_SET_IPADDRESS
    COMMAND_UNSUPPORTED_PROTOCOL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_UNSUPPORTED_PROTOCOL
    )
    OPERATION_CONFIG_LOAD_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CONFIG_LOAD_FAIL
    )
    OPERATION_SYSTEM_STATE_CHANGED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SYSTEM_STATE_CHANGED
    )
    OPERATION_3STATESWITCH_RELEASED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_3STATESWITCH_RELEASED
    )
    OPERATION_HOMMING_COMPLETED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_HOMMING_COMPLETED
    )
    OPERATION_NOT_EXIT_SAME_TCPNAME = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_NOT_EXIT_SAME_TCPNAME
    )
    OPERATION_NOT_EXIT_SAME_TOOLNAME = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_NOT_EXIT_SAME_TOOLNAME
    )
    OPERATION_EXTERNAL_STO_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_STO_SINNAL_INPUTED
    )
    OPERATION_EXTERNAL_EMG_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_EMG_SINNAL_INPUTED
    )
    OPERATION_EXTERNAL_PRS_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_PRS_SINNAL_INPUTED
    )
    OPERATION_EXTERNAL_REDUCED_SPEED_MODE_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_REDUCED_SPEED_MODE_SINNAL_INPUTED
    )
    OPERATION_COLLISION_DETECTION_STOP_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_COLLISION_DETECTION_STOP_FAIL
    )
    OPERATION_COLLISION_DETECTION_RESTART = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_COLLISION_DETECTION_RESTART
    )
    OPERATION_RECOVERY_MODE_FORCE_START = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_RECOVERY_MODE_FORCE_START
    )
    OPERATION_CONFIG_FILE_NAME_EMPTY = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CONFIG_FILE_NAME_EMPTY
    )
    OPERATION_TOOL_NAME_EXCEED_MAX_NUMBER = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_TOOL_NAME_EXCEED_MAX_NUMBER
    )
    OPERATION_TCP_NAME_EXCCED_MAX_NUMBER = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_TCP_NAME_EXCCED_MAX_NUMBER
    )
    OPERATION_CONFIG_TOOL_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CONFIG_TOOL_FAIL
    )
    OPERATION_CONFIG_TCP_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CONFIG_TCP_FAIL
    )
    OPERATION_EXTERNAL_DIRECT_TEACH_MODE_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_DIRECT_TEACH_MODE_SINNAL_INPUTED
    )
    OPERATION_EXTERNAL_MANUAL_GUIDE_STOP_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_MANUAL_GUIDE_STOP_SINNAL_INPUTED
    )
    OPERATION_MASTERING_PROCESS_NEEDED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_MASTERING_PROCESS_NEEDED
    )
    OPERATION_SYSTEM_IDLE_OFF = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SYSTEM_IDLE_OFF
    )
    OPERATION_EXTERNAL_PROTECTIVE_STOP_AUTO_RESUME_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_PROTECTIVE_STOP_AUTO_RESUME_SINNAL_INPUTED
    )
    OPERATION_REMOTE_CONTROL_MODE_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_REMOTE_CONTROL_MODE_SINNAL_INPUTED
    )
    OPERATION_SYSTEM_NOT_HAVE_CONTROL_AUTH = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SYSTEM_NOT_HAVE_CONTROL_AUTH
    )
    OPERATION_REMOTE_CONTROL_SETTING_NOT_ENABLED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_REMOTE_CONTROL_SETTING_NOT_ENABLED
    )
    OPERATION_REMOTE_CONTROL_IO_SIGNAL_OVERLAPED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_REMOTE_CONTROL_IO_SIGNAL_OVERLAPED
    )
    OPERATION_REMOTE_CONTROL_IO_SINGNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_REMOTE_CONTROL_IO_SINGNAL_INPUTED
    )
    OPERATION_REMOTE_CONTROL_IO_SINGNAL_INGNORED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_REMOTE_CONTROL_IO_SINGNAL_INGNORED
    )
    OPERATION_REMOTE_CONTROL_MODE_SINNAL_RELEASED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_REMOTE_CONTROL_MODE_SINNAL_RELEASED
    )
    OPERATION_CONFIG_USER_HOME_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CONFIG_USER_HOME_FAIL
    )
    OPERATION_CONFIG_CRC_CHECK_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CONFIG_CRC_CHECK_FAIL
    )
    OPERATION_IS_NOT_HANDGUIDE_CONDITION = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_IS_NOT_HANDGUIDE_CONDITION
    )
    OPERATION_EXTERNAL_RESUME_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_RESUME_SINNAL_INPUTED
    )
    OPERATION_EXTERNAL_RESET_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXTERNAL_RESET_SINNAL_INPUTED
    )
    OPERATION_INTERNAL_PRS_SINNAL_INPUTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_INTERNAL_PRS_SINNAL_INPUTED
    )
    COMMAND_RUN_PROGRAM = _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_RUN_PROGRAM
    OPERATION_ALREADY_RUN_PROGRAM = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ALREADY_RUN_PROGRAM
    )
    COMMAND_STOP_PROGRAM = _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_STOP_PROGRAM
    COMMAND_PAUSE_PROGRAM = _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_PAUSE_PROGRAM
    COMMAND_RESUME_PROGRAM = _dsrb.LOG_GROUP_SYSTEMFMK.COMMAND_RESUME_PROGRAM
    OPERATION_PROGRAM_NORMAL_STOP = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_NORMAL_STOP
    )
    OPERATION_PROGRAM_FORCED_STOP = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_FORCED_STOP
    )
    OPERATION_PROGRAM_FORCED_ERROR_STOP = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_FORCED_ERROR_STOP
    )
    OPERATION_PROGRAM_SW_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_SW_ERROR
    )
    OPERATION_PROGRAM_INTERNAL_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_INTERNAL_ERROR
    )
    OPERATION_PROGRAM_INIT_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_INIT_ERROR
    )
    OPERATION_PROGRAM_EMPTY_SCRIPT = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_EMPTY_SCRIPT
    )
    OPERATION_PROGRAM_RUNTIME_ERROR_START = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_RUNTIME_ERROR_START
    )
    OPERATION_PROGRAM_SYNTAX_EXCEPTION = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_SYNTAX_EXCEPTION
    )
    OPERATION_PROGRAM_SYNTAX_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_SYNTAX_ERROR
    )
    OPERATION_PROGRAM_RUNTIME_TYPE_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_RUNTIME_TYPE_ERROR
    )
    OPERATION_PROGRAM_RUNTIME_VALUE_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_RUNTIME_VALUE_ERROR
    )
    OPERATION_PROGRAM_RUNTIME_RUNTIME_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_RUNTIME_RUNTIME_ERROR
    )
    OPERATION_PROGRAM_RUNTIME_EXCEPTION = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_RUNTIME_EXCEPTION
    )
    OPERATION_PROGRAM_RUNTIME_SVM = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_RUNTIME_SVM
    )
    OPERATION_PROGRAM_RUNTIME_ERROR_END = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_PROGRAM_RUNTIME_ERROR_END
    )
    OPERATION_SERVER_START = _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SERVER_START
    OPERATION_SERVER_STOP = _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SERVER_STOP
    OPERATION_CLIENT_CONNECTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CLIENT_CONNECTED
    )
    OPERATION_CLIENT_DISCONNECTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CLIENT_DISCONNECTED
    )
    OPERATION_CLIENT_AUTHENTIFICATION_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CLIENT_AUTHENTIFICATION_FAIL
    )
    OPERATION_UNKNOWN_CLIENT_CONNECTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_UNKNOWN_CLIENT_CONNECTED
    )
    OPERATION_SEND_QUEUE_OVERFLOW = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SEND_QUEUE_OVERFLOW
    )
    OPERATION_SEND_COMMAND_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SEND_COMMAND_FAIL
    )
    OPERATION_GET_IP_ADDRESS_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_GET_IP_ADDRESS_FAIL
    )
    OPERATION_RECV_QUEUE_OVERFLOW = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_RECV_QUEUE_OVERFLOW
    )
    OPERATION_KT_CONNECT_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_KT_CONNECT_FAIL
    )
    OPERATION_KT_AUTH_FAIL = _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_KT_AUTH_FAIL
    OPERATION_SET_IP_ADDRESS_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SET_IP_ADDRESS_FAIL
    )
    OPERATION_RTSERVER_INFO = _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_RTSERVER_INFO
    OPERATION_RTSERVER_WARNING = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_RTSERVER_WARNING
    )
    OPERATION_CLIENT_AUTHENTIFICATION_COMPLETED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_CLIENT_AUTHENTIFICATION_COMPLETED
    )
    OPERATION_KT_TRY_CONNECT = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_KT_TRY_CONNECT
    )
    OPERATION_KT_CONNECTED = _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_KT_CONNECTED
    OPERATION_KT_DISCONNECTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_KT_DISCONNECTED
    )
    OPERATION_KT_AUTHENTIFICATION_COMPLETED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_KT_AUTHENTIFICATION_COMPLETED
    )
    OPERATION_ECAT_MASTER_INIT_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_MASTER_INIT_FAILED
    )
    OPERATION_ECAT_INVALID_SLAVE_TYPE = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_INVALID_SLAVE_TYPE
    )
    OPERATION_ECAT_JOBTASK_INIT_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_JOBTASK_INIT_FAILED
    )
    OPERATION_ECAT_INVALID_ENI_FILE = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_INVALID_ENI_FILE
    )
    OPERATION_ECAT_DC_NOT_SUPPORTED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_DC_NOT_SUPPORTED
    )
    OPERATION_ECAT_DC_INIT_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_DC_INIT_FAILED
    )
    OPERATION_ECAT_REG_NOTIFY_CALLBACK_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_REG_NOTIFY_CALLBACK_FAILED
    )
    OPERATION_ECAT_INVALID_VENDOR_PRODUCT_CODE = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_INVALID_VENDOR_PRODUCT_CODE
    )
    OPERATION_ECAT_CHANGE_INIT_STAT_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_CHANGE_INIT_STAT_FAILED
    )
    OPERATION_ECAT_CHANGE_PREOP_STAT_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_CHANGE_PREOP_STAT_FAILED
    )
    OPERATION_ECAT_SLAVE_CONFIG_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_SLAVE_CONFIG_FAILED
    )
    OPERATION_ECAT_CONFIG_PDO_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_CONFIG_PDO_FAILED
    )
    OPERATION_ECAT_CHANGE_SAFEOP_STAT_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_CHANGE_SAFEOP_STAT_FAILED
    )
    OPERATION_ECAT_GET_DCM_STATE_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_GET_DCM_STATE_FAILED
    )
    OPERATION_ECAT_CHANGE_OP_STAT_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_CHANGE_OP_STAT_FAILED
    )
    OPERATION_ECAT_MASTER_STOP_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_MASTER_STOP_FAILED
    )
    OPERATION_ECAT_UNREG_NOTIFY_CALLBACK_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_UNREG_NOTIFY_CALLBACK_FAILED
    )
    OPERATION_ECAT_MASTER_RELEASE_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_MASTER_RELEASE_FAILED
    )
    OPERATION_ECAT_CHANGE_BOOTSTRAP_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_CHANGE_BOOTSTRAP_FAILED
    )
    OPERATION_ECAT_OPEN_UPDATE_FILE_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_OPEN_UPDATE_FILE_FAILED
    )
    OPERATION_ECAT_INVERTER_UPDATE_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_INVERTER_UPDATE_FAILED
    )
    OPERATION_ECAT_INVALID_UPDATE_FILE = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_INVALID_UPDATE_FILE
    )
    OPERATION_ECAT_JOBTASK_RECV_RXFRAME_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_JOBTASK_RECV_RXFRAME_FAILED
    )
    OPERATION_ECAT_JOBTASK_SEND_CYCFRAME_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_JOBTASK_SEND_CYCFRAME_FAILED
    )
    OPERATION_ECAT_JOBTASK_DC_SYNC_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_JOBTASK_DC_SYNC_FAILED
    )
    OPERATION_ECAT_JOBTASK_SEND_ACYCFRAME_FAILED = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_JOBTASK_SEND_ACYCFRAME_FAILED
    )
    OPERATION_ECAT_NOTIFY_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ECAT_NOTIFY_ERROR
    )
    OPERATION_SERIAL_CONNECT_SUCCESS = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SERIAL_CONNECT_SUCCESS
    )
    OPERATION_SERIAL_CONNECT_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SERIAL_CONNECT_FAIL
    )
    OPERATION_SERIAL_DISCONNECT = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SERIAL_DISCONNECT
    )
    OPERATION_READ_SERIAL_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_READ_SERIAL_FAIL
    )
    OPERATION_READ_SERIAL_TIMEOUT = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_READ_SERIAL_TIMEOUT
    )
    OPERATION_WRITE_SERIAL_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_WRITE_SERIAL_FAIL
    )
    OPERATION_READ_CRC_ERROR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_READ_CRC_ERROR
    )
    OPERATION_UNSUPPORTED_PROTOCOL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_UNSUPPORTED_PROTOCOL
    )
    OPERATION_OUTOFRANGE_GPIO = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_OUTOFRANGE_GPIO
    )
    OPERATION_READ_SEQUENCE_ERROOR = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_READ_SEQUENCE_ERROOR
    )
    OPERATION_MODBUS_CONNECT_SUCCESS = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_MODBUS_CONNECT_SUCCESS
    )
    OPERATION_MODBUS_CONNECT_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_MODBUS_CONNECT_FAIL
    )
    OPERATION_EXIST_SAME_REGADDRESS = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXIST_SAME_REGADDRESS
    )
    OPERATION_ADDVARIABLE_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_ADDVARIABLE_FAIL
    )
    OPERATION_NOT_EXIST_SAME_NAME = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_NOT_EXIST_SAME_NAME
    )
    OPERATION_DELVARIABLE_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_DELVARIABLE_FAIL
    )
    OPERATION_SETVARIABLE_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_SETVARIABLE_FAIL
    )
    OPERATION_MODBUS_SLAVE_EXCEED_MAX_NUMBER = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_MODBUS_SLAVE_EXCEED_MAX_NUMBER
    )
    OPERATION_MODBUS_REGISTER_EXCEED_MAX_NUMBER = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_MODBUS_REGISTER_EXCEED_MAX_NUMBER
    )
    OPERATION_GETVARIABLE_FAIL = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_GETVARIABLE_FAIL
    )
    OPERATION_EXIST_SAME_NAME = (
        _dsrb.LOG_GROUP_SYSTEMFMK.OPERATION_EXIST_SAME_NAME
    )


class LogGroupMotionLib(Enum):
    """LogGroupMotionLib"""

    RC_ERROR_NO_ERROR = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_NO_ERROR
    RC_ERROR_INPUT_TOOL_WEIGHT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_TOOL_WEIGHT
    )
    RC_ERROR_INPUT_TCP = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_TCP
    RC_ERROR_INPUT_JNT_LIMIT_SET = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_JNT_LIMIT_SET
    )
    RC_ERROR_INPUT_TCP_CONSTRAINED_MOVE_RXRYRZ = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_TCP_CONSTRAINED_MOVE_RXRYRZ
    )
    RC_ERROR_INPUT_INVALID_INSTALL_POSE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_INVALID_INSTALL_POSE
    )
    RC_ERROR_INPUT_INVALID_TOOL_ESTIMATION = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_INVALID_TOOL_ESTIMATION
    )
    RC_ERROR_USERCOORD_INVALID_INPUT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_USERCOORD_INVALID_INPUT
    )
    RC_ERROR_USERCOORD_EXCEED_MAX_NUM = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_USERCOORD_EXCEED_MAX_NUM
    )
    RC_ERROR_USERCOORD = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_USERCOORD
    RC_ERROR_INPUT_TCP_INFO = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_TCP_INFO
    RC_ERROR_INPUT_TOOL_WEIGHT_COG_INFO = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_TOOL_WEIGHT_COG_INFO
    )
    RC_ERROR_INPUT_WORKPIECE_WEIGHT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_WORKPIECE_WEIGHT
    )
    RC_ERROR_INPUT_NOT_ENOUGH_VIA_POINT_NUM = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_NOT_ENOUGH_VIA_POINT_NUM
    )
    RC_ERROR_INPUT_UNEXPECTED_NEW_MTN_CMD = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_UNEXPECTED_NEW_MTN_CMD
    )
    RC_ERROR_INPUT_UNEXPECTED_NEW_MTN_CMD_BLENDING = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_UNEXPECTED_NEW_MTN_CMD_BLENDING
    )
    RC_ERROR_INPUT_CIRC_MTN_CMD = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_CIRC_MTN_CMD
    )
    RC_ERROR_INPUT_BLENDING_RAD = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_BLENDING_RAD
    )
    RC_ERROR_INPUT_OUT_OF_WORKSPACE_CMD = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_OUT_OF_WORKSPACE_CMD
    )
    RC_ERROR_INPUT_OUT_OF_USER_JOINT_LIMIT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_OUT_OF_USER_JOINT_LIMIT
    )
    RC_ERROR_INPUT_OUT_OF_USER_JVEL_LIMIT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_OUT_OF_USER_JVEL_LIMIT
    )
    RC_ERROR_INPUT_OUT_OF_USER_TVEL_LIMIT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_OUT_OF_USER_TVEL_LIMIT
    )
    RC_ERROR_INPUT_UNEXPECTED_TARGET_AXIS = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_UNEXPECTED_TARGET_AXIS
    )
    RC_ERROR_INPUT_UNEXPECTED_TARGET_TIME = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_UNEXPECTED_TARGET_TIME
    )
    RC_ERROR_INPUT_OUT_OF_TARGET_TIME_LIMIT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_OUT_OF_TARGET_TIME_LIMIT
    )
    RC_ERROR_ALTER_INPUT_PARM = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_ALTER_INPUT_PARM
    )
    RC_ERROR_INPUT_OUT_OF_TARGET_TIME_LIMIT_INFO = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_OUT_OF_TARGET_TIME_LIMIT_INFO
    )
    RC_ERROR_INPUT_NOT_VALID_MTN_PARAM = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_NOT_VALID_MTN_PARAM
    )
    RC_ERROR_INPUT_PARALLEL_AXIS = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_PARALLEL_AXIS
    )
    RC_ERROR_INPUT_ALIGN_AXIS = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_ALIGN_AXIS
    )
    RC_ERROR_CONVEYOR_NAME = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_NAME
    RC_ERROR_CONVEYOR_ID = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_ID
    RC_ERROR_CONVEYOR_INPUT_MOTION_MOD = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_INPUT_MOTION_MOD
    )
    RC_ERROR_CONVEYOR_INPUT_COMMAND = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_INPUT_COMMAND
    )
    RC_ERROR_CONVEYOR_INVALID_SETTING_INPUT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_INVALID_SETTING_INPUT
    )
    RC_ERROR_INPUT_INCORRECT_POSITION_MAX_MIN = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_INCORRECT_POSITION_MAX_MIN
    )
    RC_ERROR_INPUT_INCORRECT_FORCE_MAX_MIN = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_INCORRECT_FORCE_MAX_MIN
    )
    RC_ERROR_EST_INSTALL_POSE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_EST_INSTALL_POSE
    )
    RC_ERROR_INPUT_VIRTUAL_FENCE_SETTING = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_VIRTUAL_FENCE_SETTING
    )
    RC_ERROR_LIMIT_MAX_TCP_POSITON_VF = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_TCP_POSITON_VF
    )
    RC_ERROR_INPUT_MIN_VALUE_VF = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_MIN_VALUE_VF
    )
    RC_ERROR_DRCL_STATE_INVALID_EVENT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_DRCL_STATE_INVALID_EVENT
    )
    RC_ERROR_MATH_CALCULATION = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_MATH_CALCULATION
    )
    RC_ERROR_INPUT_CONFIG_NUDGE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_CONFIG_NUDGE
    )
    RC_ERROR_INCORRECT_REQUEST_NUDGE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INCORRECT_REQUEST_NUDGE
    )
    RC_ERROR_INPUT_REF_COORDINATE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_REF_COORDINATE
    )
    RC_ERROR_INPUT_INVALID_CONTROL_CMD = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INPUT_INVALID_CONTROL_CMD
    )
    RC_ERROR_JTS_CALIBRATION_OUT_OF_RANGE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_JTS_CALIBRATION_OUT_OF_RANGE
    )
    RC_ERROR_FTS_CALIBRATION_OUT_OF_RANGE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_FTS_CALIBRATION_OUT_OF_RANGE
    )
    RC_ERROR_LIMIT_MAX_UCPOSITON = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_UCPOSITON
    )
    RC_ERROR_LIMIT_MAX_UCVELOCITY = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_UCVELOCITY
    )
    RC_ERROR_LIMIT_MAX_JTS = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_JTS
    RC_ERROR_LIMIT_MAX_POWER = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_POWER
    )
    RC_ERROR_LIMIT_MAX_FORCE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_FORCE
    )
    RC_ERROR_LIMIT_MAX_MOMENTUM = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_MOMENTUM
    )
    RC_ERROR_LIMIT_MAX_SPEED = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_SPEED
    )
    RC_ERROR_ALTER_INVALID_MOTIONSTATUS = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_ALTER_INVALID_MOTIONSTATUS
    )
    RC_ERROR_ALTER_MOTIONREPLANNING_USING_LIMIT_VALUE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_ALTER_MOTIONREPLANNING_USING_LIMIT_VALUE
    )
    RC_ERROR_ALTER_TERMINATE_BASIC_MOTION = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_ALTER_TERMINATE_BASIC_MOTION
    )
    RC_ERROR_MOVESX_CONSTANT_SPD_UNAVAILABLE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_MOVESX_CONSTANT_SPD_UNAVAILABLE
    )
    RC_ERROR_JOG_JNT_LIMIT = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_JOG_JNT_LIMIT
    RC_ERROR_JOG_TSK_LIMIT = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_JOG_TSK_LIMIT
    RC_ERROR_JOG_SINGULARITY = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_JOG_SINGULARITY
    )
    RC_ERROR_CONVEYOR_VELOCITY = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_VELOCITY
    )
    RC_ERROR_CONVEYOR_TRACKING_SYNC_IN = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_TRACKING_SYNC_IN
    )
    RC_ERROR_CONVEYOR_TRACKING_SYNC_OUT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_TRACKING_SYNC_OUT
    )
    RC_ERROR_CONVEYOR_TRACKING_PAUSE_REQUEST = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CONVEYOR_TRACKING_PAUSE_REQUEST
    )
    RC_ERROR_MTN_COMPLIANCE_SINGULARITY = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_MTN_COMPLIANCE_SINGULARITY
    )
    RC_ERROR_INCORRECT_FORCE_RESET = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INCORRECT_FORCE_RESET
    )
    RC_ERROR_SYSTEM_EXTERNER_JOINT_VALUE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SYSTEM_EXTERNER_JOINT_VALUE
    )
    RC_ERROR_SYSTEM_JTS_VALUE_VF = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SYSTEM_JTS_VALUE_VF
    )
    RC_ERROR_SYSTEM_JTS_VALUE_COMP_CTRL = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SYSTEM_JTS_VALUE_COMP_CTRL
    )
    RC_ERROR_SYSTEM_JTS_VALUE_AUTO_COMPENSATION = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SYSTEM_JTS_VALUE_AUTO_COMPENSATION
    )
    RC_ERROR_SYSTEM_JTS_VALUE_TEACHING_CTRL = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SYSTEM_JTS_VALUE_TEACHING_CTRL
    )
    RC_ERROR_SYSTEM_JTS_CAL = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SYSTEM_JTS_CAL
    RC_ERROR_FLOAT_COLLISION_DIST_LIMIT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_FLOAT_COLLISION_DIST_LIMIT
    )
    RC_ERROR_MTN_SINGULARITY = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_MTN_SINGULARITY
    )
    RC_ERROR_LIMIT_MAX_TARGET_JOINT_VELOCITY = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_LIMIT_MAX_TARGET_JOINT_VELOCITY
    )
    RC_ERROR_CALC_INVERSE_KINEMATICS = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_CALC_INVERSE_KINEMATICS
    )
    RC_ERROR_SYSTEM_JTS_VALUE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SYSTEM_JTS_VALUE
    )
    RC_ERROR_HW_FTS_LIMIT = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_HW_FTS_LIMIT
    RC_ERROR_APP_FAIL_JTS_CALIBRATION = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_APP_FAIL_JTS_CALIBRATION
    )
    RC_ERROR_APP_FAIL_MEASURE_INSTALLPOSE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_APP_FAIL_MEASURE_INSTALLPOSE
    )
    RC_ERROR_APP_FAIL_MEASURE_TOOL_INFO = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_APP_FAIL_MEASURE_TOOL_INFO
    )
    RC_ERROR_APP_FAIL_MEASURE_TCP = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_APP_FAIL_MEASURE_TCP
    )
    RC_ERROR_SAFETY_STO = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_STO
    RC_ERROR_SAFETY_SBC = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_SBC
    RC_ERROR_SAFETY_SS1 = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_SS1
    RC_ERROR_SAFETY_SS2 = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_SS2
    RC_ERROR_SAFETY_EMG = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_EMG
    RC_ERROR_SAFETY_PRS = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_PRS
    RC_ERROR_SAFETY_SOS = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_SOS
    RC_ERROR_SAFETY_JOINT_SLP = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_JOINT_SLP
    )
    RC_ERROR_SAFETY_JOINT_SLS = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_JOINT_SLS
    )
    RC_ERROR_SAFETY_JOINT_SLT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_JOINT_SLT
    )
    RC_ERROR_SAFETY_COLLISION = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_COLLISION
    )
    RC_ERROR_SAFETY_TCP_SLP = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_TCP_SLP
    RC_ERROR_SAFETY_TCP_SLO = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_TCP_SLO
    RC_ERROR_SAFETY_TCP_SLS = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_TCP_SLS
    RC_ERROR_SAFETY_TCP_SLF = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_TCP_SLF
    RC_ERROR_SAFETY_MOMENTUM = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_MOMENTUM
    )
    RC_ERROR_SAFETY_POWER = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_POWER
    RC_ERROR_SAFETY_ENABLE_SWITCH_RELEASE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_ENABLE_SWITCH_RELEASE
    )
    RC_ERROR_SAFETY_NUDGE_INPUT = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_SAFETY_NUDGE_INPUT
    )
    RC_ERROR_MANUAL_GUIDING_SAFETY = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_MANUAL_GUIDING_SAFETY
    )
    RC_ERROR_FORCE_INPUT = _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_FORCE_INPUT
    RC_ERROR_WELDING_INPUT_PARAM = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_WELDING_INPUT_PARAM
    )
    RC_ERROR_WELDING_WEAVE_FUNC = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_WELDING_WEAVE_FUNC
    )
    RC_ERROR_WELDING_WELD_PROCESS = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_WELDING_WELD_PROCESS
    )
    RC_ERROR_WELDING_WEAVE_FUNC_INFO = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_WELDING_WEAVE_FUNC_INFO
    )
    RC_ERROR_WELDING_WELD_PROCESS_INFO = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_WELDING_WELD_PROCESS_INFO
    )
    RC_ERROR_INSIDE_SINGULARITY_REGION = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_INSIDE_SINGULARITY_REGION
    )
    RC_ERROR_OUTSIDE_SINGULARITY_REGION = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_OUTSIDE_SINGULARITY_REGION
    )
    RC_ERROR_ZONE_COLLISIONCHECK_IN_VIRTUALMODE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_ZONE_COLLISIONCHECK_IN_VIRTUALMODE
    )
    RC_ERROR_ZONE_NOT_COLLISIONCHECK_IN_VIRTUALMODE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_ZONE_NOT_COLLISIONCHECK_IN_VIRTUALMODE
    )
    RC_ERROR_PALLETIZINGMODE = (
        _dsrb.LOG_GROUP_MOTIONLIB.RC_ERROR_PALLETIZINGMODE
    )


class LogGroupInverter(Enum):
    """LogGroupInverter"""

    OPERATION_INVT_NO_ERROR = _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_NO_ERROR
    OPERATION_INVT_UNKNOWN_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_UNKNOWN_ERROR
    )
    OPERATION_INVT_SDO_COMM_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_SDO_COMM_ERROR
    )
    OPERATION_INVT_OVER_CURRENT_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_OVER_CURRENT_ERROR
    )
    OPERATION_INVT_OVER_VOLTAGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_OVER_VOLTAGE_ERROR
    )
    OPERATION_INVT_UNDER_VOLTAGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_UNDER_VOLTAGE_ERROR
    )
    OPERATION_INVT_OVER_TEMPERATURE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_OVER_TEMPERATURE_ERROR
    )
    OPERATION_INVT_UNDER_TEMPERATURE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_UNDER_TEMPERATURE_ERROR
    )
    OPERATION_INVT_SUPPLY_24V_LOW_VOLTAGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_SUPPLY_24V_LOW_VOLTAGE_ERROR
    )
    OPERATION_INVT_SUPPLY_5V_LOW_VOLTAGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_SUPPLY_5V_LOW_VOLTAGE_ERROR
    )
    OPERATION_INVT_SUPPLY_17V_LOW_VOLTAGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_SUPPLY_17V_LOW_VOLTAGE_ERROR
    )
    OPERATION_INVT_SUPPLY_24BRK_LOW_VOLTAGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_SUPPLY_24BRK_LOW_VOLTAGE_ERROR
    )
    OPERATION_INVT_SUPPLY_DSPIO_VOLTAGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_SUPPLY_DSPIO_VOLTAGE_ERROR
    )
    OPERATION_INVT_SUPPLY_CORE_VOLTAGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_SUPPLY_CORE_VOLTAGE_ERROR
    )
    OPERATION_INVT_CURRENT_OFFSET_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_CURRENT_OFFSET_ERROR
    )
    OPERATION_INVT_INCREMENTAL_SENSOR_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_INCREMENTAL_SENSOR_ERROR
    )
    OPERATION_INVT_ABSENCODER_MULT_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_ABSENCODER_MULT_ERROR
    )
    OPERATION_INVT_ABSENCODER_CRC_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_ABSENCODER_CRC_ERROR
    )
    OPERATION_INVT_OVER_SPEED_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_OVER_SPEED_ERROR
    )
    OPERATION_INVT_POSTIION_LIMIT_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_POSTIION_LIMIT_ERROR
    )
    OPERATION_INVT_HALL_SENSOR_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_HALL_SENSOR_ERROR
    )
    OPERATION_INVT_HALL_ANGLE_DETECTION_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_HALL_ANGLE_DETECTION_ERROR
    )
    OPERATION_INVT_ETHERCAT_COMM_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_ETHERCAT_COMM_ERROR
    )
    OPERATION_INVT_HEARTBEAT_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_HEARTBEAT_ERROR
    )
    OPERATION_INVT_DIFFICULT_START_UP_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_DIFFICULT_START_UP_ERROR
    )
    OPERATION_INVT_POSITION_FOLLOWING_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_POSITION_FOLLOWING_ERROR
    )
    OPERATION_INVT_POSITION_REFERENCE_LIMIT_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_POSITION_REFERENCE_LIMIT_ERROR
    )
    OPERATION_INVT_STO_ERROR = _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_STO_ERROR
    OPERATION_INVT_EXTERNAL_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_EXTERNAL_ERROR
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_LIMIT = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_LIMIT
    )
    OPERATION_INVT_OVERLOAD_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_OVERLOAD_ERROR
    )
    OPERATION_INVT_HW_OVER_CURRENT_SHORT_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_HW_OVER_CURRENT_SHORT_ERROR
    )
    OPERATION_INVT_BRAKE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_BRAKE_ERROR
    )
    OPERATION_INVT_POSITION_SENSOR_INDEX_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_POSITION_SENSOR_INDEX_ERROR
    )
    OPERATION_INVT_POSITION_SENSOR_PULSE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_POSITION_SENSOR_PULSE_ERROR
    )
    OPERATION_INVT_CONTROLBOARD_TYPE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_CONTROLBOARD_TYPE_ERROR
    )
    OPERATION_INVT_HARMONICDRIVE_TYPE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_HARMONICDRIVE_TYPE_ERROR
    )
    OPERATION_INVT_EEPROM_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_EEPROM_ERROR
    )
    OPERATION_INVT_PRECHARGE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_PRECHARGE_ERROR
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_LIMIT_1 = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_LIMIT_1
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_LIMIT_2 = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_LIMIT_2
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_COMPARE = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_COMPARE
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_RAPID_CHANGE = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_RAPID_CHANGE
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_1 = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_1
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_2 = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_2
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_COMPARE_SAME = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_COMPARE_SAME
    )
    OPERATION_INVT_CURRENT_UNBALANCE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_CURRENT_UNBALANCE_ERROR
    )
    OPERATION_INVT_BOARD_OVER_TEMPERATURE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_BOARD_OVER_TEMPERATURE_ERROR
    )
    OPERATION_INVT_BOARD_UNDER_TEMPERATURE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_BOARD_UNDER_TEMPERATURE_ERROR
    )
    OPERATION_INVT_INCREMENTAL_ENCODER_NO_COUNT = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_INCREMENTAL_ENCODER_NO_COUNT
    )
    OPERATION_INVT_INC_ABS_POS_DIFFERENCE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_INC_ABS_POS_DIFFERENCE_ERROR
    )
    OPERATION_INVT_INC_ABS_SPEED_DIFFERENCE_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_INC_ABS_SPEED_DIFFERENCE_ERROR
    )
    OPERATION_INVT_JTS_SEQ_NUNBER_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JTS_SEQ_NUNBER_ERROR
    )
    OPERATION_INVT_JTS_CRC32_ERROR = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JTS_CRC32_ERROR
    )
    OPERATION_INVT_INVAILD_EEPROM_PARAMETER = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_INVAILD_EEPROM_PARAMETER
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_3 = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_3
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_4 = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_4
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_5 = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_5
    )
    OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_6 = (
        _dsrb.LOG_GROUP_INVERTER.OPERATION_INVT_JOINT_TORQUE_SENSOR_NOT_CHANGE_6
    )


class LogGroupSafetyController(Enum):
    """LogGroupSafetyController"""

    SAFETY_CONTROLLER_ERROR_NUMBER_START = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.SAFETY_CONTROLLER_ERROR_NUMBER_START
    )
    OPERATION_RS422_SEQUENCE_NUMBER_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_RS422_SEQUENCE_NUMBER_ERROR
    )
    OPERATION_RS422_CRC32_CHECK_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_RS422_CRC32_CHECK_ERROR
    )
    OPERATION_RS422_UNKNOWN_COMMAND = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_RS422_UNKNOWN_COMMAND
    )
    OPERATION_RS422_COMMUNICATION_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_RS422_COMMUNICATION_ERROR
    )
    OPERATION_ETHERCAT_COMMUNICATION_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_ETHERCAT_COMMUNICATION_ERROR
    )
    OPERATION_CROSS_CHECK_BUFFER_OVERFLOW_BETWEEN_CPUS = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_CROSS_CHECK_BUFFER_OVERFLOW_BETWEEN_CPUS
    )
    OPERATION_HANDGUIDE_IS_NOT_ALLOWED = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_HANDGUIDE_IS_NOT_ALLOWED
    )
    OPERATION_MOTION_CROSS_CHECK_ERROR_BETWEEN_CPUS = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_MOTION_CROSS_CHECK_ERROR_BETWEEN_CPUS
    )
    OPERATION_MOTION_MONITORING_PERIOD_OVERUN = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_MOTION_MONITORING_PERIOD_OVERUN
    )
    OPERATION_EMG_INPUT_CROSS_CHECK_ERROR_BETWEEN_CPUS = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EMG_INPUT_CROSS_CHECK_ERROR_BETWEEN_CPUS
    )
    OPERATION_EMG_INPUT_BEYOND_VOLTAGE_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EMG_INPUT_BEYOND_VOLTAGE_RANGE
    )
    OPERATION_PRS_INPUT_CROSS_CHECK_ERROR_BETWEEN_CPUS = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PRS_INPUT_CROSS_CHECK_ERROR_BETWEEN_CPUS
    )
    OPERATION_PRS_INPUT_BEYOND_VOLTAGE_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PRS_INPUT_BEYOND_VOLTAGE_RANGE
    )
    OPERATION_SAFETY_OUT_CROSS_CHECK_ERROR_BETWEEN_CPUS = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_OUT_CROSS_CHECK_ERROR_BETWEEN_CPUS
    )
    OPERATION_SAFETY_OUT_FEEDBACK_DIFFENENT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_OUT_FEEDBACK_DIFFENENT
    )
    OPERATION_SAFETY_INPUT_CROSS_CHECK_ERROR_BETWEEN_CPUS = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_INPUT_CROSS_CHECK_ERROR_BETWEEN_CPUS
    )
    OPERATION_CROSS_CHECK_ERROR_SAFETY_STATE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_CROSS_CHECK_ERROR_SAFETY_STATE
    )
    OPERATION_INVERTER_TEMP_BEYOND_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_TEMP_BEYOND_RANGE
    )
    OPERATION_INVERTER_DATA_SEQUENCE_NUMBER_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_DATA_SEQUENCE_NUMBER_ERROR
    )
    OPERATION_INVERTER_DATA_CRC32_CHECK_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_DATA_CRC32_CHECK_ERROR
    )
    OPERATION_INVERTER_JTS_SEQUENCE_NUMBER_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_JTS_SEQUENCE_NUMBER_ERROR
    )
    OPERATION_INVERTER_JTS_CRC32_CHECK_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_JTS_CRC32_CHECK_ERROR
    )
    OPERATION_INVERTER_ETEHERCAT_TIMEOUT_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_ETEHERCAT_TIMEOUT_ERROR
    )
    OPERATION_UNDEFINED_INSTRUCTION_EXCEPTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_UNDEFINED_INSTRUCTION_EXCEPTION
    )
    OPERATION_PREPATCH_ABORT_EXCEPTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PREPATCH_ABORT_EXCEPTION
    )
    OPERATION_DATA_ABORT_EXCEPTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DATA_ABORT_EXCEPTION
    )
    OPERATION_EXCHANGE_DATA_SEQUENCE_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_DATA_SEQUENCE_ERROR
    )
    OPERATION_EXCHANGE_DATA_CRC32_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_DATA_CRC32_ERROR
    )
    OPERATION_EXCHANGE_CLEARCMD_SEQUENCE_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_CLEARCMD_SEQUENCE_ERROR
    )
    OPERATION_EXCHANGE_CLEARCMD_CRC32_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_CLEARCMD_CRC32_ERROR
    )
    OPERATION_EXCHANGE_UPDATEDATA_SEQUENCE_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_UPDATEDATA_SEQUENCE_ERROR
    )
    OPERATION_EXCHANGE_UPDATEDATA_CRC32_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_UPDATEDATA_CRC32_ERROR
    )
    OPERATION_EXCHANGE_INTREQ_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_INTREQ_ERROR
    )
    OPERATION_EXCHANGE_INTREQ_SEQUENCE_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_INTREQ_SEQUENCE_ERROR
    )
    OPERATION_EXCHANGE_INTREQ_CRC32_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_INTREQ_CRC32_ERROR
    )
    OPERATION_EXCHANGE_RS422_COMPARE_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_EXCHANGE_RS422_COMPARE_ERROR
    )
    OPERATION_SAFETY_FUNCTION_STO = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_STO
    )
    OPERATION_SAFETY_FUNCTION_RS1_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_RS1_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_SS1_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_SS1_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_SS2_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_SS2_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_EMG_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_EMG_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_PRS_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_PRS_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_SOS_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_SOS_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_JOINT_SLP_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_JOINT_SLP_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_JOINT_SLS_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_JOINT_SLS_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_JOINT_SLT_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_JOINT_SLT_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_COLLISION_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_COLLISION_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_TCP_SLP_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_TCP_SLP_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_TCP_ORIENTATION_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_TCP_ORIENTATION_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_TCP_SLS_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_TCP_SLS_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_TCP_FORCE_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_TCP_FORCE_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_MOMENTUM_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_MOMENTUM_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_POWER_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_POWER_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_SELF_BODY_COLLISION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_SELF_BODY_COLLISION
    )
    OPERATION_SAFETY_FUNCTION_PROTECTIVE_ZONE_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_PROTECTIVE_ZONE_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_ENCODER_CMP_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_ENCODER_CMP_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_JTS_CMP_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_JTS_CMP_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_3_CURRENT_SUM_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_3_CURRENT_SUM_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_CURRENT_2_TRQ_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_CURRENT_2_TRQ_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_JOINT_FOLLOWING_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_JOINT_FOLLOWING_VIOLATION
    )
    OPERATION_SAFETY_FUNCTION_NUDGE_VIOLATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_SAFETY_FUNCTION_NUDGE_VIOLATION
    )
    OPERATION_INVERTER_1_2V_BEYOND_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_1_2V_BEYOND_RANGE
    )
    OPERATION_INVERTER_3_3V_BEYOND_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_3_3V_BEYOND_RANGE
    )
    OPERATION_INVERTER_5V_BEYOND_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_5V_BEYOND_RANGE
    )
    OPERATION_INVERTER_17V_BEYOND_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_17V_BEYOND_RANGE
    )
    OPERATION_INVERTER_24BV_BEYOND_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_24BV_BEYOND_RANGE
    )
    OPERATION_INVERTER_24CV_BEYOND_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_24CV_BEYOND_RANGE
    )
    OPERATION_INVERTER_48V_BEYOND_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVERTER_48V_BEYOND_RANGE
    )
    OPERATION_DETECT_S24V_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_S24V_DEVIATION
    )
    OPERATION_DETECT_S6V_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_S6V_DEVIATION
    )
    OPERATION_DETECT_S5V_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_S5V_DEVIATION
    )
    OPERATION_DETECT_S3V3_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_S3V3_DEVIATION
    )
    OPERATION_DETECT_S1V2_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_S1V2_DEVIATION
    )
    OPERATION_DETECT_NS12V_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_NS12V_DEVIATION
    )
    OPERATION_DETECT_NS5V_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_NS5V_DEVIATION
    )
    OPERATION_DETECT_NS3V3_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_NS3V3_DEVIATION
    )
    OPERATION_DETECT_NS2V5_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_NS2V5_DEVIATION
    )
    OPERATION_DETECT_STO_RELAY_MALFUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_STO_RELAY_MALFUNCTION
    )
    OPERATION_DETECT_EMF_DATA_BUS_MALFUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_EMF_DATA_BUS_MALFUNCTION
    )
    OPERATION_DETECT_EMF_ADDRESS_BUS_MALFUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_EMF_ADDRESS_BUS_MALFUNCTION
    )
    OPERATION_DETECT_SRAM_RUNTIME_TEST_FAIL = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_SRAM_RUNTIME_TEST_FAIL
    )
    OPERATION_DETECT_SPI_2__BUS__MALFUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_SPI_2__BUS__MALFUNCTION
    )
    OPERATION_DETECT_SPI_3__BUS__MALFUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_SPI_3__BUS__MALFUNCTION
    )
    OPERATION_DETECT_CPU_TEMP_BEYOUN_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_TEMP_BEYOUN_RANGE
    )
    OPERATION_DETECT_BOARD_TEMP_BEYOUN_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_BOARD_TEMP_BEYOUN_RANGE
    )
    OPERATION_DETECT_CPU_CLOCK_MALFUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_CLOCK_MALFUNCTION
    )
    OPERATION_DETECT_MOTOR_SOLIDSTATE_CIRCUIT_BRAKE_MALFUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_MOTOR_SOLIDSTATE_CIRCUIT_BRAKE_MALFUNCTION
    )
    OPERATION_DETECT_BREAK_SOLIDSTATE_CIRCUIT_BRAKE_MALFUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_BREAK_SOLIDSTATE_CIRCUIT_BRAKE_MALFUNCTION
    )
    OPERATION_DETECT_MOTOR48V_OVERVOLTAGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_MOTOR48V_OVERVOLTAGE
    )
    OPERATION_DETECT_MOTOR48V_UNDERVOLTAGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_MOTOR48V_UNDERVOLTAGE
    )
    OPERATION_DETECT_BRAKE24V_OVERVOLTAGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_BRAKE24V_OVERVOLTAGE
    )
    OPERATION_DETECT_BRAKE24V_UNDERVOLTAGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_BRAKE24V_UNDERVOLTAGE
    )
    OPERATION_DETECT_PRECHARGE_UNDERVOLTAGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_PRECHARGE_UNDERVOLTAGE
    )
    OPERATION_DETECT_MOTOR_OVERCURRENT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_MOTOR_OVERCURRENT
    )
    OPERATION_DETECT_BRAKE_OVERCURRENT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_BRAKE_OVERCURRENT
    )
    OPERATION_DETECT_LOGIC_OVERCURRENT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_LOGIC_OVERCURRENT
    )
    OPERATION_DETECT_IO_OVERCURRENT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_IO_OVERCURRENT
    )
    OPERATION_DETECT_MOTOR_FET_FALUT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_MOTOR_FET_FALUT
    )
    OPERATION_DETECT_BRAKE_FET_FALUT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_BRAKE_FET_FALUT
    )
    OPERATION_DETECT_PRECHARGE_OVERCURRENT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_PRECHARGE_OVERCURRENT
    )
    OPERATION_DETECT_STO_RELAY_FAULT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_STO_RELAY_FAULT
    )
    OPERATION_DETECT_DISCREPANCY_MOTOR_CURRENT_A = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_DISCREPANCY_MOTOR_CURRENT_A
    )
    OPERATION_DETECT_DISCREPANCY_MOTOR_CURRENT_B = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_DISCREPANCY_MOTOR_CURRENT_B
    )
    OPERATION_DETECT_DISCREPANCY_BRAKE_VOLTAGE_A = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_DISCREPANCY_BRAKE_VOLTAGE_A
    )
    OPERATION_DETECT_DISCREPANCY_BRAKE_VOLTAGE_B = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_DISCREPANCY_BRAKE_VOLTAGE_B
    )
    OPERATION_DETECT_DISCREPANCY_MOTOR_VOLTAGE_A = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_DISCREPANCY_MOTOR_VOLTAGE_A
    )
    OPERATION_DETECT_DISCREPANCY_MOTOR_VOLTAGE_B = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_DISCREPANCY_MOTOR_VOLTAGE_B
    )
    OPERATION_DETECT_DISCREPANCY_BRAKE_CURRENT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_DISCREPANCY_BRAKE_CURRENT
    )
    OPERATION_DETECT_WATCHDOG_ERROR = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_WATCHDOG_ERROR
    )
    OPERATION_DETECT_CPU_UNDERTEMPERATURE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_UNDERTEMPERATURE
    )
    OPERATION_DETECT_BOARD_UNDERTEMPERATURE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_BOARD_UNDERTEMPERATURE
    )
    OPERATION_DETECT_CPU_OVERTEMPERATURE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_OVERTEMPERATURE
    )
    OPERATION_DETECT_BOARD_OVERTEMPERATURE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_BOARD_OVERTEMPERATURE
    )
    OPERATION_DETECT_CPU_SRAM_ECC_FAULT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_SRAM_ECC_FAULT
    )
    OPERATION_DETECT_CPU_FLASH_ECC_FAULT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_FLASH_ECC_FAULT
    )
    OPERATION_DETECT_CPU_FLASH_CRC_FAULT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_FLASH_CRC_FAULT
    )
    OPERATION_DETECT_JTSSENSOR_FAULT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_JTSSENSOR_FAULT
    )
    OPERATION_DETECT_MOTION_CAL_CMP_FAIL = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_MOTION_CAL_CMP_FAIL
    )
    OPERATION_DETECT_PRECHARGE_FET_FAULT = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_PRECHARGE_FET_FAULT
    )
    OPERATION_DETECT_IO5V_DEVIATION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_IO5V_DEVIATION
    )
    OPERATION_PARAM_INVALID_SYSTEM_STATE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_SYSTEM_STATE
    )
    OPERATION_PARAM_INVALID_CURRENT_TOOL = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_CURRENT_TOOL
    )
    OPERATION_PARAM_INVALID_CURRENT_TCP = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_CURRENT_TCP
    )
    OPERATION_PARAM_INVALID_GENERAL_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_GENERAL_RANGE
    )
    OPERATION_PARAM_INVALID_JOINT_RANGE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_JOINT_RANGE
    )
    OPERATION_PARAM_INVALID_SAFETY_FUNCTION = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_SAFETY_FUNCTION
    )
    OPERATION_PARAM_INVALID_INSTALL_POSE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_INSTALL_POSE
    )
    OPERATION_PARAM_INVALID_SAFETY_IO_SETTING = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_SAFETY_IO_SETTING
    )
    OPERATION_PARAM_INVALID_VIRTUAL_WALL = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_VIRTUAL_WALL
    )
    OPERATION_PARAM_INVALID_SAFE_ZONE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_SAFE_ZONE
    )
    OPERATION_PARAM_INVALID_SAFE_ZONE_ENABLE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_SAFE_ZONE_ENABLE
    )
    OPERATION_PARAM_INVALID_PROTECTED_ZONE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_PROTECTED_ZONE
    )
    OPERATION_PARAM_INVALID_COLLISION_MUTE_ZONE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_COLLISION_MUTE_ZONE
    )
    OPERATION_PARAM_INVALID_TOOL_ORIENTATION_LIMIT_ZONE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_TOOL_ORIENTATION_LIMIT_ZONE
    )
    OPERATION_PARAM_INVALID_TOOL_SHAPE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_TOOL_SHAPE
    )
    OPERATION_PARAM_INVALID_CONFIG_TOOL = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_CONFIG_TOOL
    )
    OPERATION_PARAM_INVALID_CONFIG_TCP = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_CONFIG_TCP
    )
    OPERATION_PARAM_INVALID_NOT_EXIST_TOOL_SHAPE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_INVALID_NOT_EXIST_TOOL_SHAPE
    )
    OPERATION_PARAM_FAILED_TO_SELECT_TOOL_SHAPE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_FAILED_TO_SELECT_TOOL_SHAPE
    )
    OPERATION_PARAM_FAILED_TO_DELETE_TOOL_SHAPE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_FAILED_TO_DELETE_TOOL_SHAPE
    )
    OPERATION_PARAM_FAILED_TO_ADD_SAFETY_ZONE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_FAILED_TO_ADD_SAFETY_ZONE
    )
    OPERATION_PARAM_FAILED_TO_DELETE_SAFETY_ZONE = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_PARAM_FAILED_TO_DELETE_SAFETY_ZONE
    )
    OPERATION_INVALID_REMOTE_CONTROL_MODE_SINNAL = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_INVALID_REMOTE_CONTROL_MODE_SINNAL
    )
    OPERATION_DETECT_CPU_RESERVED1 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED1
    )
    OPERATION_DETECT_CPU_RESERVED2 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED2
    )
    OPERATION_DETECT_CPU_RESERVED3 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED3
    )
    OPERATION_DETECT_CPU_RESERVED4 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED4
    )
    OPERATION_DETECT_CPU_RESERVED5 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED5
    )
    OPERATION_DETECT_CPU_RESERVED6 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED6
    )
    OPERATION_DETECT_CPU_RESERVED7 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED7
    )
    OPERATION_DETECT_CPU_RESERVED8 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED8
    )
    OPERATION_DETECT_CPU_RESERVED9 = (
        _dsrb.LOG_GROUP_SAFETYCONTROLLER.OPERATION_DETECT_CPU_RESERVED9
    )


class OpenConnError(Enum):
    """OpenConnError"""

    NO_ERROR = _dsrb.OpenConnError.NO_ERROR
    CREATE_ROBOT_CONTROL_ERROR = _dsrb.OpenConnError.CREATE_ROBOT_CONTROL_ERROR
    OPEN_CONNECTION_ERROR = _dsrb.OpenConnError.OPEN_CONNECTION_ERROR
    INITIALIZE_TP_ERROR = _dsrb.OpenConnError.INITIALIZE_TP_ERROR
    MANAGE_ACCESS_CONTROL_ERROR = (
        _dsrb.OpenConnError.MANAGE_ACCESS_CONTROL_ERROR
    )
    GET_CONTROL_RIGHT_ERROR = _dsrb.OpenConnError.GET_CONTROL_RIGHT_ERROR


class ServoOnError(Enum):
    """ServoOnError"""

    NO_ERROR = _dsrb.ServoOnError.NO_ERROR
    NO_ROBOT_CONTROL_ERROR = _dsrb.ServoOnError.NO_ROBOT_CONTROL_ERROR
    SET_ROBOT_MODE_ERROR = _dsrb.ServoOnError.SET_ROBOT_MODE_ERROR
    SET_ROBOT_CONTROL_ERROR = _dsrb.ServoOnError.SET_ROBOT_CONTROL_ERROR
    GET_STATE_STANDBY_ERROR = _dsrb.ServoOnError.GET_STATE_STANDBY_ERROR
    SET_SAFETY_MODE_ERROR = _dsrb.ServoOnError.SET_SAFETY_MODE_ERROR
    GET_ROBOT_STATE_ERROR = _dsrb.ServoOnError.GET_ROBOT_STATE_ERROR


class ServoOffError(Enum):
    """ServoOffError"""

    NO_ERROR = _dsrb.ServoOffError.NO_ERROR
    NO_ROBOT_CONTROL_ERROR = _dsrb.ServoOffError.NO_ROBOT_CONTROL_ERROR
    SET_SERVO_OFF_ERROR = _dsrb.ServoOffError.SET_SERVO_OFF_ERROR
    GET_ROBOT_STATE_ERROR = _dsrb.ServoOffError.GET_ROBOT_STATE_ERROR


class CloseConnError(Enum):
    """CloseConnError"""

    NO_ERROR = _dsrb.CloseConnError.NO_ERROR
    NO_ROBOT_CONTROL_ERROR = _dsrb.CloseConnError.NO_ROBOT_CONTROL_ERROR
    LOSE_CONTROL_RIGHT_ERROR = _dsrb.CloseConnError.LOSE_CONTROL_RIGHT_ERROR


class ActiveMotion(Enum):
    """ActiveMotion"""

    NO_MOTION_IN_ACTION = _dsrb.ActiveMotion.NO_MOTION_IN_ACTION
    MOTION_BEING_CALCULATED = _dsrb.ActiveMotion.MOTION_BEING_CALCULATED
    MOTION_IN_OPERATION = _dsrb.ActiveMotion.MOTION_IN_OPERATION


class TrajState(Enum):
    """TrajState"""

    STOP = _dsrb.TrajState.STOP
    STOPPING = _dsrb.TrajState.STOPPING
    TRAPJ = _dsrb.TrajState.TRAPJ
    ATTRJ = _dsrb.TrajState.ATTRJ
    ATTRL = _dsrb.TrajState.ATTRL
    PLAYJ = _dsrb.TrajState.PLAYJ
